name: express-playground
services:
- environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
    repo: drivn/express-playground
  name: express-playground
  envs:
  - key: FOO
    value: "${_self.FOO}"
    scope: BUILD_AND_RUN_TIME
